---
- name: Upgrade all packages
  become: yes
  pacman:
    update_cache: yes
    upgrade: yes

- import_tasks: Archlinux/sublime-text.yml

- name: Define common_packages.
  set_fact:
    common_packages: "{{ __common_packages }}"
  when: common_packages is not defined

- name: Install common packages.
  become: yes
  pacman: "name={{ item }} state=latest"
  with_items: '{{common_packages}}'
